// Simple design system guardrail script.
// Flags common violations: raw Material widgets, hard-coded padding/colors,
// and material.dart imports outside the renderer layer.
import 'dart:io';

final _forbiddenPatterns = <String, RegExp>{
  'Raw SnackBar': RegExp(r'[^A-Za-z]SnackBar\('),
  'Raw AlertDialog': RegExp(r'AlertDialog\('),
  'Raw showDialog': RegExp(r'showDialog<'),
  'Raw BottomSheet': RegExp(r'showModalBottomSheet'),
  'Raw TextField': RegExp(r'[^A-Za-z]TextField\('),
  'Raw ElevatedButton': RegExp(r'ElevatedButton\('),
  'Raw OutlinedButton': RegExp(r'OutlinedButton\('),
  'Raw TextButton': RegExp(r'TextButton\('),
  'Raw FloatingActionButton': RegExp(r'FloatingActionButton\('),
  'Raw ListTile': RegExp(r'[^A-Za-z]ListTile\('),
  'Raw CircularProgressIndicator': RegExp(r'CircularProgressIndicator\('),
  'Hard-coded EdgeInsets.all (non-zero)': RegExp(r'EdgeInsets\.all\((?!0\))'),
  'Hard-coded EdgeInsets.symmetric (non-zero)': RegExp(
    r'EdgeInsets\.symmetric\((?!vertical: 0|horizontal: 0)',
  ),
  'Hard-coded Color hex': RegExp(r'Color\(0x[0-9A-Fa-f]{6,8}\)'),
};

final _allowlistPaths = <String>[
  'tool/',
  'test/',
  'lib/core/theme/',
  'lib/renderer/',
  '.dart_tool/',
];

final _materialImportPattern =
    RegExp("import\\s+[\"']package:flutter/material\\.dart[\"']");

final _materialImportAllowlist = <String>[
  'lib/renderer/',
  // generated by Flutter Intl plugin; safe exception; do not expand
  'lib/generated/l10n.dart',
];

void main(List<String> args) {
  final repoRoot = Directory.current;
  final violations = <String>[];
  final allViolations = <String>[];
  final mode = _modeFromArgs(args);
  final baseline = _baselineFromArgs(args);
  final writeBaselinePath = _writeBaselineFromArgs(args);

  for (final file in repoRoot
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))) {
    final relativePath = file.path.replaceFirst(
      repoRoot.path + Platform.pathSeparator,
      '',
    );
    final normalizedPath = relativePath.replaceAll('\\', '/');
    final content = file.readAsStringSync();
    if (normalizedPath.startsWith('lib/') &&
        _materialImportPattern.hasMatch(content) &&
        !_materialImportAllowlist.any(normalizedPath.startsWith)) {
      final violation =
          '$normalizedPath => Material import outside lib/renderer/';
      allViolations.add(violation);
      if (!baseline.contains(violation)) {
        violations.add(violation);
      }
    }

    if (_allowlistPaths.any(normalizedPath.startsWith)) continue;

    _forbiddenPatterns.forEach((label, pattern) {
      if (pattern.hasMatch(content)) {
        final violation = '$normalizedPath => $label';
        allViolations.add(violation);
        if (!baseline.contains(violation)) {
          violations.add(violation);
        }
      }
    });
  }

  if (writeBaselinePath != null && writeBaselinePath.isNotEmpty) {
    final file = File(writeBaselinePath);
    file.writeAsStringSync(
      (allViolations.toSet().toList()..sort()).join('\n'),
    );
  }

  if (violations.isEmpty) {
    stdout.writeln('Design system check passed ?.');
    return;
  }

  stderr.writeln('Design system violations found:');
  for (final v in violations) {
    stderr.writeln(' - $v');
  }
  if (mode == _Mode.warn) {
    return;
  }
  exitCode = 1;
}

enum _Mode { warn, fail }

_Mode _modeFromArgs(List<String> args) {
  for (final arg in args) {
    if (arg.startsWith('--mode=')) {
      final value = arg.substring('--mode='.length);
      return value == 'warn' ? _Mode.warn : _Mode.fail;
    }
  }
  return _Mode.fail;
}

Set<String> _baselineFromArgs(List<String> args) {
  final baselinePath = _argValue(args, '--baseline=');
  if (baselinePath == null || baselinePath.isEmpty) return {};
  final file = File(baselinePath);
  if (!file.existsSync()) return {};
  return file
      .readAsLinesSync()
      .map((line) => line.trim())
      .where((line) => line.isNotEmpty)
      .toSet();
}

String? _writeBaselineFromArgs(List<String> args) {
  return _argValue(args, '--write-baseline=');
}

String? _argValue(List<String> args, String prefix) {
  for (final arg in args) {
    if (arg.startsWith(prefix)) {
      return arg.substring(prefix.length);
    }
  }
  return null;
}
