part of 'today_bloc.dart';

TodayState _todayStateWithProfile(
  TodayState current,
  TodayUserProfile? profile,
) {
  if (current.isLoading) {
    return TodayState.loading(
      profile: profile,
      shareOwed: current.shareOwed,
      sharePaidToMe: current.sharePaidToMe,
      shareDrafts: current.shareDrafts,
      harmonyPromptTick: current.harmonyPromptTick,
      hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
      npsPromptTick: current.npsPromptTick,
      hasShownNpsPrompt: current.hasShownNpsPrompt,
      gratitudeStatus: current.gratitudeStatus,
      personalGratitudeStatus: current.personalGratitudeStatus,
      notificationPromptTick: current.notificationPromptTick,
      hasShownNotificationPrompt: current.hasShownNotificationPrompt,
      activeChoreCount: current.activeChoreCount,
      shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
      shouldPromptInviteShare: current.shouldPromptInviteShare,
      shouldPromptPreferences: current.shouldPromptPreferences,
      shouldPromptHouseNorms: current.shouldPromptHouseNorms,
      memberCapJoinRequests: current.memberCapJoinRequests,
      memberCapJoinResolution: current.memberCapJoinResolution,
      housePulse: current.housePulse,
    );
  }

  if (current.message != null || current.error != null) {
    return TodayState.failure(
      profile: profile,
      message: current.message,
      error: current.error,
      shareOwed: current.shareOwed,
      sharePaidToMe: current.sharePaidToMe,
      shareDrafts: current.shareDrafts,
      shareErrorMessage: current.shareErrorMessage,
      harmonyPromptTick: current.harmonyPromptTick,
      hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
      npsPromptTick: current.npsPromptTick,
      hasShownNpsPrompt: current.hasShownNpsPrompt,
      gratitudeStatus: current.gratitudeStatus,
      personalGratitudeStatus: current.personalGratitudeStatus,
      notificationPromptTick: current.notificationPromptTick,
      hasShownNotificationPrompt: current.hasShownNotificationPrompt,
      activeChoreCount: current.activeChoreCount,
      shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
      shouldPromptInviteShare: current.shouldPromptInviteShare,
      shouldPromptPreferences: current.shouldPromptPreferences,
      shouldPromptHouseNorms: current.shouldPromptHouseNorms,
      memberCapJoinRequests: current.memberCapJoinRequests,
      memberCapJoinResolution: current.memberCapJoinResolution,
      housePulse: current.housePulse,
    );
  }

  return TodayState.loaded(
    activeTasks: current.activeTasks,
    draftTasks: current.draftTasks,
    shareOwed: current.shareOwed,
    sharePaidToMe: current.sharePaidToMe,
    shareDrafts: current.shareDrafts,
    profile: profile,
    shareErrorMessage: current.shareErrorMessage,
    harmonyPromptTick: current.harmonyPromptTick,
    hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
    npsPromptTick: current.npsPromptTick,
    hasShownNpsPrompt: current.hasShownNpsPrompt,
    gratitudeStatus: current.gratitudeStatus,
    notificationPromptTick: current.notificationPromptTick,
    hasShownNotificationPrompt: current.hasShownNotificationPrompt,
    activeChoreCount: current.activeChoreCount,
    shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
    shouldPromptInviteShare: current.shouldPromptInviteShare,
    shouldPromptPreferences: current.shouldPromptPreferences,
    shouldPromptHouseNorms: current.shouldPromptHouseNorms,
    memberCapJoinRequests: current.memberCapJoinRequests,
    memberCapJoinResolution: current.memberCapJoinResolution,
    housePulse: current.housePulse,
  );
}

TodayState _todayStateWithoutInvitePrompt(TodayState current) {
  if (current.isLoading) {
    return TodayState.loading(
      profile: current.profile,
      shareOwed: current.shareOwed,
      sharePaidToMe: current.sharePaidToMe,
      shareDrafts: current.shareDrafts,
      gratitudeStatus: current.gratitudeStatus,
      harmonyPromptTick: current.harmonyPromptTick,
      hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
      npsPromptTick: current.npsPromptTick,
      hasShownNpsPrompt: current.hasShownNpsPrompt,
      notificationPromptTick: current.notificationPromptTick,
      hasShownNotificationPrompt: current.hasShownNotificationPrompt,
      activeChoreCount: current.activeChoreCount,
      shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
      shouldPromptInviteShare: false,
      shouldPromptPreferences: current.shouldPromptPreferences,
      shouldPromptHouseNorms: current.shouldPromptHouseNorms,
      memberCapJoinRequests: current.memberCapJoinRequests,
      memberCapJoinResolution: current.memberCapJoinResolution,
      housePulse: current.housePulse,
    );
  }

  if (current.message != null || current.error != null) {
    return TodayState.failure(
      profile: current.profile,
      message: current.message,
      error: current.error,
      shareOwed: current.shareOwed,
      sharePaidToMe: current.sharePaidToMe,
      shareDrafts: current.shareDrafts,
      shareErrorMessage: current.shareErrorMessage,
      gratitudeStatus: current.gratitudeStatus,
      harmonyPromptTick: current.harmonyPromptTick,
      hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
      npsPromptTick: current.npsPromptTick,
      hasShownNpsPrompt: current.hasShownNpsPrompt,
      notificationPromptTick: current.notificationPromptTick,
      hasShownNotificationPrompt: current.hasShownNotificationPrompt,
      activeChoreCount: current.activeChoreCount,
      shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
      shouldPromptInviteShare: false,
      shouldPromptPreferences: current.shouldPromptPreferences,
      shouldPromptHouseNorms: current.shouldPromptHouseNorms,
      memberCapJoinRequests: current.memberCapJoinRequests,
      memberCapJoinResolution: current.memberCapJoinResolution,
      housePulse: current.housePulse,
    );
  }

  return TodayState.loaded(
    activeTasks: current.activeTasks,
    draftTasks: current.draftTasks,
    shareOwed: current.shareOwed,
    sharePaidToMe: current.sharePaidToMe,
    shareDrafts: current.shareDrafts,
    profile: current.profile,
    shareErrorMessage: current.shareErrorMessage,
    gratitudeStatus: current.gratitudeStatus,
    harmonyPromptTick: current.harmonyPromptTick,
    hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
    npsPromptTick: current.npsPromptTick,
    hasShownNpsPrompt: current.hasShownNpsPrompt,
    notificationPromptTick: current.notificationPromptTick,
    hasShownNotificationPrompt: current.hasShownNotificationPrompt,
    activeChoreCount: current.activeChoreCount,
    shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
    shouldPromptInviteShare: false,
    shouldPromptPreferences: current.shouldPromptPreferences,
    shouldPromptHouseNorms: current.shouldPromptHouseNorms,
    memberCapJoinRequests: current.memberCapJoinRequests,
    memberCapJoinResolution: current.memberCapJoinResolution,
    housePulse: current.housePulse,
  );
}

TodayState _todayStateWithoutFlatmatePrompt(TodayState current) {
  if (current.isLoading) {
    return TodayState.loading(
      profile: current.profile,
      shareOwed: current.shareOwed,
      shareDrafts: current.shareDrafts,
      gratitudeStatus: current.gratitudeStatus,
      harmonyPromptTick: current.harmonyPromptTick,
      hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
      npsPromptTick: current.npsPromptTick,
      hasShownNpsPrompt: current.hasShownNpsPrompt,
      notificationPromptTick: current.notificationPromptTick,
      hasShownNotificationPrompt: current.hasShownNotificationPrompt,
      activeChoreCount: current.activeChoreCount,
      shouldPromptFlatmateInviteShare: false,
      shouldPromptInviteShare: current.shouldPromptInviteShare,
      shouldPromptPreferences: current.shouldPromptPreferences,
      shouldPromptHouseNorms: current.shouldPromptHouseNorms,
      memberCapJoinRequests: current.memberCapJoinRequests,
      memberCapJoinResolution: current.memberCapJoinResolution,
      housePulse: current.housePulse,
    );
  }

  if (current.message != null || current.error != null) {
    return TodayState.failure(
      profile: current.profile,
      message: current.message,
      error: current.error,
      shareOwed: current.shareOwed,
      sharePaidToMe: current.sharePaidToMe,
      shareDrafts: current.shareDrafts,
      shareErrorMessage: current.shareErrorMessage,
      gratitudeStatus: current.gratitudeStatus,
      harmonyPromptTick: current.harmonyPromptTick,
      hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
      npsPromptTick: current.npsPromptTick,
      hasShownNpsPrompt: current.hasShownNpsPrompt,
      notificationPromptTick: current.notificationPromptTick,
      hasShownNotificationPrompt: current.hasShownNotificationPrompt,
      activeChoreCount: current.activeChoreCount,
      shouldPromptFlatmateInviteShare: false,
      shouldPromptInviteShare: current.shouldPromptInviteShare,
      shouldPromptPreferences: current.shouldPromptPreferences,
      shouldPromptHouseNorms: current.shouldPromptHouseNorms,
      memberCapJoinRequests: current.memberCapJoinRequests,
      memberCapJoinResolution: current.memberCapJoinResolution,
      housePulse: current.housePulse,
    );
  }

  return TodayState.loaded(
    activeTasks: current.activeTasks,
    draftTasks: current.draftTasks,
    shareOwed: current.shareOwed,
    sharePaidToMe: current.sharePaidToMe,
    shareDrafts: current.shareDrafts,
    profile: current.profile,
    shareErrorMessage: current.shareErrorMessage,
    gratitudeStatus: current.gratitudeStatus,
    harmonyPromptTick: current.harmonyPromptTick,
    hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
    npsPromptTick: current.npsPromptTick,
    hasShownNpsPrompt: current.hasShownNpsPrompt,
    notificationPromptTick: current.notificationPromptTick,
    hasShownNotificationPrompt: current.hasShownNotificationPrompt,
    activeChoreCount: current.activeChoreCount,
    shouldPromptFlatmateInviteShare: false,
    shouldPromptInviteShare: current.shouldPromptInviteShare,
    shouldPromptPreferences: current.shouldPromptPreferences,
    shouldPromptHouseNorms: current.shouldPromptHouseNorms,
    memberCapJoinRequests: current.memberCapJoinRequests,
    memberCapJoinResolution: current.memberCapJoinResolution,
    housePulse: current.housePulse,
  );
}

TodayState _todayStateWithoutMemberCapPrompt(TodayState current) {
  if (current.isLoading) {
    return TodayState.loading(
      profile: current.profile,
      shareOwed: current.shareOwed,
      sharePaidToMe: current.sharePaidToMe,
      shareDrafts: current.shareDrafts,
      gratitudeStatus: current.gratitudeStatus,
      harmonyPromptTick: current.harmonyPromptTick,
      hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
      npsPromptTick: current.npsPromptTick,
      hasShownNpsPrompt: current.hasShownNpsPrompt,
      notificationPromptTick: current.notificationPromptTick,
      hasShownNotificationPrompt: current.hasShownNotificationPrompt,
      activeChoreCount: current.activeChoreCount,
      shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
      shouldPromptInviteShare: current.shouldPromptInviteShare,
      shouldPromptPreferences: current.shouldPromptPreferences,
      shouldPromptHouseNorms: current.shouldPromptHouseNorms,
      memberCapJoinRequests: null,
      memberCapJoinResolution: current.memberCapJoinResolution,
      housePulse: current.housePulse,
    );
  }

  if (current.message != null || current.error != null) {
    return TodayState.failure(
      profile: current.profile,
      message: current.message,
      error: current.error,
      shareOwed: current.shareOwed,
      sharePaidToMe: current.sharePaidToMe,
      shareDrafts: current.shareDrafts,
      shareErrorMessage: current.shareErrorMessage,
      gratitudeStatus: current.gratitudeStatus,
      harmonyPromptTick: current.harmonyPromptTick,
      hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
      npsPromptTick: current.npsPromptTick,
      hasShownNpsPrompt: current.hasShownNpsPrompt,
      notificationPromptTick: current.notificationPromptTick,
      hasShownNotificationPrompt: current.hasShownNotificationPrompt,
      activeChoreCount: current.activeChoreCount,
      shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
      shouldPromptInviteShare: current.shouldPromptInviteShare,
      shouldPromptPreferences: current.shouldPromptPreferences,
      shouldPromptHouseNorms: current.shouldPromptHouseNorms,
      memberCapJoinRequests: null,
      memberCapJoinResolution: current.memberCapJoinResolution,
      housePulse: current.housePulse,
    );
  }

  return TodayState.loaded(
    activeTasks: current.activeTasks,
    draftTasks: current.draftTasks,
    shareOwed: current.shareOwed,
    sharePaidToMe: current.sharePaidToMe,
    shareDrafts: current.shareDrafts,
    profile: current.profile,
    shareErrorMessage: current.shareErrorMessage,
    gratitudeStatus: current.gratitudeStatus,
    harmonyPromptTick: current.harmonyPromptTick,
    hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
    npsPromptTick: current.npsPromptTick,
    hasShownNpsPrompt: current.hasShownNpsPrompt,
    notificationPromptTick: current.notificationPromptTick,
    hasShownNotificationPrompt: current.hasShownNotificationPrompt,
    activeChoreCount: current.activeChoreCount,
    shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
    shouldPromptInviteShare: current.shouldPromptInviteShare,
    shouldPromptPreferences: current.shouldPromptPreferences,
    shouldPromptHouseNorms: current.shouldPromptHouseNorms,
    memberCapJoinRequests: null,
    memberCapJoinResolution: current.memberCapJoinResolution,
    housePulse: current.housePulse,
  );
}

TodayState _todayStateWithHousePulse(
  TodayState current,
  HousePulsePayload? housePulse,
) {
  if (current.isLoading) {
    return TodayState.loading(
      profile: current.profile,
      shareOwed: current.shareOwed,
      sharePaidToMe: current.sharePaidToMe,
      shareDrafts: current.shareDrafts,
      gratitudeStatus: current.gratitudeStatus,
      personalGratitudeStatus: current.personalGratitudeStatus,
      harmonyPromptTick: current.harmonyPromptTick,
      hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
      npsPromptTick: current.npsPromptTick,
      hasShownNpsPrompt: current.hasShownNpsPrompt,
      notificationPromptTick: current.notificationPromptTick,
      hasShownNotificationPrompt: current.hasShownNotificationPrompt,
      activeChoreCount: current.activeChoreCount,
      shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
      shouldPromptInviteShare: current.shouldPromptInviteShare,
      shouldPromptPreferences: current.shouldPromptPreferences,
      shouldPromptHouseNorms: current.shouldPromptHouseNorms,
      memberCapJoinRequests: current.memberCapJoinRequests,
      memberCapJoinResolution: current.memberCapJoinResolution,
      housePulse: housePulse,
    );
  }

  if (current.message != null || current.error != null) {
    return TodayState.failure(
      profile: current.profile,
      message: current.message,
      error: current.error,
      shareOwed: current.shareOwed,
      sharePaidToMe: current.sharePaidToMe,
      shareDrafts: current.shareDrafts,
      shareErrorMessage: current.shareErrorMessage,
      gratitudeStatus: current.gratitudeStatus,
      personalGratitudeStatus: current.personalGratitudeStatus,
      harmonyPromptTick: current.harmonyPromptTick,
      hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
      npsPromptTick: current.npsPromptTick,
      hasShownNpsPrompt: current.hasShownNpsPrompt,
      notificationPromptTick: current.notificationPromptTick,
      hasShownNotificationPrompt: current.hasShownNotificationPrompt,
      activeChoreCount: current.activeChoreCount,
      shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
      shouldPromptInviteShare: current.shouldPromptInviteShare,
      shouldPromptPreferences: current.shouldPromptPreferences,
      shouldPromptHouseNorms: current.shouldPromptHouseNorms,
      memberCapJoinRequests: current.memberCapJoinRequests,
      memberCapJoinResolution: current.memberCapJoinResolution,
      housePulse: housePulse,
    );
  }

  return TodayState.loaded(
    activeTasks: current.activeTasks,
    draftTasks: current.draftTasks,
    shareOwed: current.shareOwed,
    sharePaidToMe: current.sharePaidToMe,
    shareDrafts: current.shareDrafts,
    profile: current.profile,
    shareErrorMessage: current.shareErrorMessage,
    gratitudeStatus: current.gratitudeStatus,
    personalGratitudeStatus: current.personalGratitudeStatus,
    harmonyPromptTick: current.harmonyPromptTick,
    hasShownHarmonyPrompt: current.hasShownHarmonyPrompt,
    npsPromptTick: current.npsPromptTick,
    hasShownNpsPrompt: current.hasShownNpsPrompt,
    notificationPromptTick: current.notificationPromptTick,
    hasShownNotificationPrompt: current.hasShownNotificationPrompt,
    activeChoreCount: current.activeChoreCount,
    shouldPromptFlatmateInviteShare: current.shouldPromptFlatmateInviteShare,
    shouldPromptInviteShare: current.shouldPromptInviteShare,
    shouldPromptPreferences: current.shouldPromptPreferences,
    shouldPromptHouseNorms: current.shouldPromptHouseNorms,
    memberCapJoinRequests: current.memberCapJoinRequests,
    memberCapJoinResolution: current.memberCapJoinResolution,
    housePulse: housePulse,
  );
}
